### ISSUE TITLE
Accidentally force pushed over autograder changes

### ISSUE THREAD

**Issue by uncjackg** [comp426-2022-spring/a01-uncjackg#2]
Hey @jdmar3 , I didn't check github and accidentally pushed a commit that wiped out changes to the autograder, which is causing the action to fail again. There was a successful workflow run earlier (before my latest commit), so do I need to do anything else for this assignment? If so, is there a way I can get those commits back?

Thanks!

**Comment by camsimba** [comment]
Hey @uncjackg, let me see if I can help some!

If you need an old file from your git, you can use `git checkout <commit id> <filename>` to grab the old version of the file and bring it back to your current working area. You can then use `git add <filename>` and then push it, and it should restore the old version of the file to Github. You can use this to grab the correct autograder file that you need but overwrote from whichever commit it previously existed in and push it to your current version.

Just as a sidenote, make sure you always fetch/pull before pushing to a control source. Definitely don't want to overwrite a colleague's code accidentally!

Let me know if this doesn't work, and we can work a little more on it!

**Comment by uncjackg** [comment]
Got it @camsimba ! thank you
